/* ════════════════════════════
            DATA
════════════════════════════ */

export const places = [
  {
    id: "home",
    icon: "🏠",
    name: "My Home",
    addr: "12 Maple Avenue",
    desc: "Starting point for all routes. A cozy two-story house next to the traffic light.",
    color: "#F4A32A",
    cx: 210,
    cy: 320,
    w: 54,
    h: 38,
  },
  {
    id: "supermarket",
    icon: "🛒",
    name: "Supermarket",
    addr: "45 Maple Avenue",
    desc: "Open Monday to Saturday, 7 am – 9 pm. Great prices and fresh produce.",
    color: "#3A86FF",
    cx: 210,
    cy: 120,
    w: 70,
    h: 42,
  },
  {
    id: "school",
    icon: "🏫",
    name: "Maplewood School",
    addr: "8 Oak Street",
    desc: "Primary and secondary school. Rated one of the best in the district.",
    color: "#FF6B6B",
    cx: 370,
    cy: 120,
    w: 72,
    h: 42,
  },
  {
    id: "park",
    icon: "🌳",
    name: "Central Park",
    addr: "Oak St & Maple Ave",
    desc: "Beautiful green space with a fountain, benches, and walking paths. Open 24 h.",
    color: "#5BAD6F",
    cx: 370,
    cy: 270,
    w: 100,
    h: 90,
  },
  {
    id: "hospital",
    icon: "🏥",
    name: "City Hospital",
    addr: "2 River Road",
    desc: "Emergency services available 24/7. Pharmacy inside. Easy parking.",
    color: "#FF4D6D",
    cx: 90,
    cy: 490,
    w: 72,
    h: 42,
  },
  {
    id: "subway",
    icon: "🚇",
    name: "Subway Station",
    addr: "Pine Boulevard",
    desc: "Line A & B. Trains every 8 minutes during rush hour.",
    color: "#6C63FF",
    cx: 370,
    cy: 490,
    w: 70,
    h: 42,
  },
  {
    id: "cafe",
    icon: "☕",
    name: "The Corner Café",
    addr: "1 Oak St (NE corner)",
    desc: "Artisan coffee, pastries, and free Wi-Fi. Open 6 am – 8 pm.",
    color: "#D4845A",
    cx: 510,
    cy: 120,
    w: 70,
    h: 40,
  },
  {
    id: "library",
    icon: "📚",
    name: "Public Library",
    addr: "30 Elm Lane",
    desc: "Free books, study rooms, and public computers. Open Tue–Sun 9 am – 7 pm.",
    color: "#4ECDC4",
    cx: 510,
    cy: 320,
    w: 68,
    h: 40,
  },
  {
    id: "pharmacy",
    icon: "💊",
    name: "Pharmacy",
    addr: "50 Maple Avenue",
    desc: "24-hour pharmacy. Prescriptions and over-the-counter medicines.",
    color: "#2EC4B6",
    cx: 90,
    cy: 320,
    w: 65,
    h: 38,
  },
  {
    id: "bank",
    icon: "🏦",
    name: "National Bank",
    addr: "15 Pine Boulevard",
    desc: "ATM available 24/7. Open Mon–Fri 9 am – 4 pm.",
    color: "#E9C46A",
    cx: 210,
    cy: 490,
    w: 65,
    h: 38,
  },
  {
    id: "store",
    icon: "🛍️",
    name: "Fashion Store",
    addr: "20 Oak Street",
    desc: "Clothing, shoes, and accessories. Weekend sales every Friday night.",
    color: "#E76F51",
    cx: 510,
    cy: 490,
    w: 68,
    h: 38,
  },
];

export const routes = [
  {
    from: "🏠 Home",
    to: "🛒 Supermarket",
    emoji: "🛒",
    steps: [
      '<span class="route-keyword">Go straight on</span> Maple Avenue heading <strong>north</strong> for two blocks.',
      "The Supermarket is on your <strong>left side</strong>, next to the pharmacy.",
      '<span class="route-keyword">It is in front of</span> the park entrance. <span class="route-keyword">Five minutes by foot.</span>',
    ],
  },
  {
    from: "🏠 Home",
    to: "☕ Corner Café",
    emoji: "☕",
    steps: [
      '<span class="route-keyword">Go straight on</span> Maple Avenue heading <strong>north</strong> for one block.',
      'At the traffic light, <span class="route-keyword">turn right</span> onto Oak Street.',
      'Walk one block east. <span class="route-keyword">Cross the street</span> at the pedestrian <em>crossing</em>.',
      'The Café is on the <em>corner</em>, <span class="route-keyword">in front of</span> the school. <span class="route-keyword">Seven minutes on foot.</span>',
    ],
  },
  {
    from: "🏠 Home",
    to: "🌳 Central Park",
    emoji: "🌳",
    steps: [
      '<span class="route-keyword">Go straight on</span> Maple Avenue heading <strong>north</strong>.',
      'At the first <em>traffic light</em>, <span class="route-keyword">turn right</span> on Oak Street.',
      'Walk straight for two blocks. The Park is <span class="route-keyword">in front of you</span>, past the <em>roundabout</em>.',
      '<span class="route-keyword">Five minutes by foot</span> from home.',
    ],
  },
  {
    from: "🏠 Home",
    to: "🏥 City Hospital",
    emoji: "🏥",
    steps: [
      '<span class="route-keyword">Turn left</span> at the <em>traffic light</em> on Maple Avenue heading <strong>south</strong>.',
      'Walk two blocks south to Pine Boulevard. <span class="route-keyword">Turn left</span> onto River Road.',
      '<span class="route-keyword">Cross the street</span> at the pedestrian <em>bridge</em>.',
      'The Hospital is the large building <span class="route-keyword">next to</span> the river. <span class="route-keyword">Ten minutes by foot.</span>',
    ],
  },
  {
    from: "🏠 Home",
    to: "🚇 Subway Station",
    emoji: "🚇",
    steps: [
      "Walk <strong>east</strong> on Pine Boulevard for three blocks.",
      'At the <em>roundabout</em>, <span class="route-keyword">turn right</span> and go south half a block.',
      'The Station entrance is <span class="route-keyword">next to</span> the Fashion Store, <span class="route-keyword">in front of</span> the park.',
      '<span class="route-keyword">Eight minutes by foot.</span>',
    ],
  },
];
